# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "uas" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/daa631cb-41a7-4754-b82f-8e464e6731ac";
      fsType = "btrfs";
      options = [ "ssd,discard,noatime,compress=zstd,subvol=@" ];
    };

  fileSystems."/home" =
    {
      device = "/dev/disk/by-uuid/daa631cb-41a7-4754-b82f-8e464e6731ac";
      fsType = "btrfs";
      options = [ "ssd,discard,noatime,compress=zstd,subvol=@home" ];
    };

  fileSystems."/nix" =
    {
      device = "/dev/disk/by-uuid/daa631cb-41a7-4754-b82f-8e464e6731ac";
      fsType = "btrfs";
      options = [ "ssd,discard,noatime,compress=zstd,subvol=@nix" ];
    };

  fileSystems."/boot/efi" =
    {
      device = "/dev/disk/by-uuid/108C-10A8";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu = {
    amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
